Fixes to Research Data in Python lesson
alan-turing-institute/rsd-engineeringcourse pull request #8
Opened 2021-01-06 13:52 UTC by jack89roberts

Fixed a few errors and typos I came across in the "Research Data in Python" lesson, as described below.

ch00data/
========

010exemplar
--------------
- Add link to geopy, nose and imageio PyPi pages (in case people need to install them)
- Fix error caused by using Nominatim with default user_agent (set user agent to "rsd-course")
- Fix bad indent in geolocate function definition.

ch01data/
========

061internet
------------
- Replace use of Google maps API (which needs an API key) with the Yandex API that's now used elsewhere in the course.
- Add a cell to display the map returned by the API

064JsonYamlXML
------------------
- Replace deprecated yaml.load (with default unsafe loader) wiith yaml.safe_load and link to docs explaining this.

065MazeSaved
----------------
- Replace deprecated yaml.load (with default unsafe loader) wiith yaml.safe_load

072Plotting
------------
- Fix `import IPython.display import Image` to `from IPython.display import Image`

110capstone
-------------
- Fix broken URL to 010exemplar HTML page.
- Fix `unexpected keyword argument 'lang' in self.geocoder = geopy.geocoders.Yandex(lang="en_US")` by switching to `geopy.Nominatim(user_agent="rsd-course")` as used in 010exemplar.

2021-01-06 14:02 UTC, jack89roberts commented
I did all these in a python 3.8 environment, but I see the course is meant to be python 3.6 so I'll check them again on that instead. It seems like the build is failing due to something I haven't changed, though.

2021-01-08 10:36 UTC, jemrobinson requested changes
In ch01data/082NumPy.ipynb
- You've lost the output of `values` after `values = np.linspace(0, math.pi, 100)`
- ... and the figure after `from matplotlib import pyplot as plt; plt.plot(values, np.sin(values))`
- ... and the output of `np.zeros([3, 4, 2])`

2021-01-08 10:36 UTC, jemrobinson commented on ch02git/index.md
> +mountain or two depending on your definition.
Is this removal of the index file deliberate or accidental?

2021-01-08 11:18 UTC, jack89roberts commented on ch02git/index.md
> +mountain or two depending on your definition.
Fixed the missing outputs in 082Numpy.ipynb. The last 3 commits including the change to index.md appeared on my fork automatically from something, I guess Travis, they're not changes I made intentionally. I've deleted those commits and cancelled the Travis build on my fork. But let's see if they re-appear here when the Travis build from this repo is finished.

2021-01-08 11:36 UTC, jemrobinson approved these changes

2021-01-08 11:37 UTC, jemrobinson commented on ch01data/064JsonYamlXML.ipynb
> +    "**Suupplementary Materials:** `yaml.safe_load` is preferred over `yaml.load` to avoid executing arbitrary code in untrusted files. See [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load
```suggestion
    "**Supplementary Materials:** `yaml.safe_load` is preferred over `yaml.load` to avoid executing arbitrary code in untrusted files. See [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) for details."
```

2021-01-08 13:30 UTC, merged